/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Cormorant Garamond"', "Georgia", "serif"],
        sans: ['"Plus Jakarta Sans"', "system-ui", "sans-serif"],
      },
      colors: {
        ivory: { DEFAULT: "#FAF9F6", 2: "#EEECE7", 3: "#E4E0DA" },
        soft: "#FFFFFF",
        sand: "#EEECE7",
        charcoal: "#141210",
        taupe: "#68625D",
        burgundy: "#58130E",
        oxblood: { DEFAULT: "#58130E", light: "#7A2A22", soft: "#F3E9E6", deep: "#3E0C09" },
        bronze: "#58130E",
        terracotta: "#8A4D3B",
        walnut: "#4A3B32",
        brass: "#C5A880",
        line: "#DDD8D2",
        night: { DEFAULT: "#141210", 2: "#1B1815", line: "#2B2622" },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      letterSpacing: { label: "0.18em" },
      transitionTimingFunction: { out: "cubic-bezier(0.22, 1, 0.36, 1)" },
      maxWidth: { site: "1680px" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        marquee: { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
        shimmer: { "0%": { maskPosition: "150% 0", WebkitMaskPosition: "150% 0" }, "100%": { maskPosition: "-50% 0", WebkitMaskPosition: "-50% 0" } },
        kenburns: { "0%": { transform: "scale(1)" }, "100%": { transform: "scale(1.09)" } },
        fillbar: { "0%": { transform: "scaleX(0)" }, "100%": { transform: "scaleX(1)" } },
        scrollline: {
          "0%": { transform: "scaleY(0)", transformOrigin: "top" },
          "50%": { transform: "scaleY(1)", transformOrigin: "top" },
          "51%": { transform: "scaleY(1)", transformOrigin: "bottom" },
          "100%": { transform: "scaleY(0)", transformOrigin: "bottom" },
        },
      },
      animation: {
        scrollline: "scrollline 2.4s cubic-bezier(0.65, 0, 0.35, 1) infinite",
        marquee: "marquee 48s linear infinite",
        "marquee-slow": "marquee 70s linear infinite",
        shimmer: "shimmer 2.8s cubic-bezier(0.65, 0, 0.35, 1) infinite",
        kenburns: "kenburns 8s linear forwards",
        fillbar: "fillbar 6.8s linear forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
