import { img } from "@/content/images";

// Placeholder project archive. Titles are neutral project types, not real project names.
// Replace `isPlaceholder`, imagery and copy with actual Suvi Interior project data when supplied.

export const projectCategories = [
  { key: "all", label: "All" },
  { key: "residential", label: "Residential" },
  { key: "kitchens", label: "Kitchens" },
  { key: "living", label: "Living" },
  { key: "bedroom", label: "Bedroom" },
  { key: "furniture", label: "Furniture" },
  { key: "other", label: "Other" },
];

export const projects = [
  {
    slug: "contemporary-residence",
    title: "Contemporary Residence",
    type: "Full Home Interior",
    category: "residential",
    location: "Nashik",
    year: null,
    featured: true,
    isPlaceholder: true,
    summary: "A complete residential interior where living, dining and private spaces share one calm material language.",
    hero: img.livingPanels,
    gallery: [img.livingGarden, img.openPlan, img.diningDark, img.bedroomSlats],
    concept: "Warm wood panelling runs through the home, tying together the living area, dining space and bedrooms so that each room feels part of a single idea rather than a series of separate decisions.",
    materials: ["Wood veneer panelling", "Matte laminates", "Stone surfaces", "Linen and neutral textiles"],
    features: ["Open-plan living and dining", "Integrated storage walls", "Coordinated bedroom joinery", "Layered lighting"],
  },
  {
    slug: "modern-kitchen",
    title: "Modern Kitchen",
    type: "Modular Kitchen",
    category: "kitchens",
    location: "Nashik",
    year: null,
    featured: true,
    isPlaceholder: true,
    summary: "A dark, tactile modular kitchen with generous storage and a restrained palette of wood and stone.",
    hero: img.kitchenWoodDark,
    gallery: [img.kitchenDark, img.kitchenBlack, img.kitchenTap, img.kitchenWhite],
    concept: "Cabinetry is treated as architecture — tall units read as a single dark wall while the oak island introduces warmth and a place to gather.",
    materials: ["Dark matte laminate", "Oak veneer", "Stone countertop", "Slim metal handles"],
    features: ["Tall pantry units", "Island with seating", "Concealed appliances", "Under-cabinet lighting"],
  },
  {
    slug: "luxury-bedroom",
    title: "Luxury Bedroom",
    type: "Bedroom Interior",
    category: "bedroom",
    location: "Nashik",
    year: null,
    featured: true,
    isPlaceholder: true,
    summary: "A master bedroom built around a full-height wood headboard wall and quiet, concealed storage.",
    hero: img.bedroomLux,
    gallery: [img.bedroomDark, img.bedroomBeige, img.bedroomWood, img.bedroomSlats],
    concept: "The headboard wall becomes the room's single gesture; wardrobes recede into the same finish so the space stays uncluttered.",
    materials: ["Walnut-tone veneer", "Upholstered panels", "Brass lighting", "Soft linen"],
    features: ["Full-height headboard wall", "Concealed wardrobes", "Integrated bedside units", "Ambient lighting"],
  },
  {
    slug: "minimal-living-space",
    title: "Warm Minimal Residence",
    type: "Living Room",
    category: "living",
    location: "Nashik",
    year: null,
    featured: true,
    isPlaceholder: true,
    summary: "A living room reduced to essentials — proportion, light and a few well-made pieces.",
    hero: img.livingBeige,
    gallery: [img.livingMinimal, img.livingView, img.livingSoft, img.livingGrey],
    concept: "Every element earns its place. Low furniture keeps sightlines open, while a single feature wall provides depth without noise.",
    materials: ["Soft plaster tones", "Light oak", "Bouclé and linen", "Matte stone"],
    features: ["Open sightlines", "Low-profile seating", "Feature wall", "Hidden storage"],
  },
  {
    slug: "custom-tv-unit",
    title: "Custom TV Unit",
    type: "TV Unit & Wall System",
    category: "furniture",
    location: "Nashik",
    year: null,
    featured: false,
    isPlaceholder: true,
    summary: "A floor-to-ceiling entertainment wall with concealed cable management and display niches.",
    hero: img.tvWall,
    gallery: [img.tvShelves, img.tvUnit, img.tvCabinets, img.tvFireplace],
    concept: "The unit is composed as a wall rather than a piece of furniture — a rhythm of closed volumes and open shelves that frame the screen.",
    materials: ["Dark veneer", "Fluted panels", "Metal shelving", "Integrated LED"],
    features: ["Cable management", "Display niches", "Closed storage", "Backlit panels"],
  },
  {
    slug: "full-home-interior",
    title: "Full Home Interior",
    type: "Complete Interior",
    category: "residential",
    location: "Nashik",
    year: null,
    featured: false,
    isPlaceholder: true,
    summary: "End-to-end interior for a family home — living, dining, kitchen and bedrooms designed as one.",
    hero: img.livingLounge,
    gallery: [img.livingArches, img.livingBeams, img.diningWood, img.bedroomGrey],
    concept: "A shared palette of warm wood, ivory and stone lets each room have its own character while the home reads as a whole.",
    materials: ["Wood veneer", "Natural stone", "Neutral textiles", "Warm metals"],
    features: ["Whole-home coordination", "Custom furniture throughout", "Dining and kitchen integration", "Bedroom joinery"],
  },
  {
    slug: "dining-and-kitchen",
    title: "Dining & Kitchen",
    type: "Dining Space",
    category: "other",
    location: "Nashik",
    year: null,
    featured: false,
    isPlaceholder: true,
    summary: "A solid wood dining table anchors an open kitchen-dining space designed for everyday meals and gatherings.",
    hero: img.diningWood,
    gallery: [img.diningWarm, img.diningDesk, img.kitchenIsland, img.diningDark],
    concept: "Kitchen cabinetry steps back visually so the dining table — and the people around it — take centre stage.",
    materials: ["Solid wood table", "Matte cabinetry", "Pendant lighting", "Stone flooring"],
    features: ["Open kitchen-dining plan", "Custom dining furniture", "Crockery storage", "Pendant lighting"],
  },
  {
    slug: "wardrobe-and-storage",
    title: "Wardrobe & Storage",
    type: "Custom Furniture",
    category: "furniture",
    location: "Nashik",
    year: null,
    featured: false,
    isPlaceholder: true,
    summary: "Floor-to-ceiling wardrobe and storage system made to measure for a compact bedroom.",
    hero: img.wardrobe,
    gallery: [img.doors, img.sideTable, img.console, img.bedroomSoft],
    concept: "Storage is planned first, then made invisible — a continuous run of wood with open shelving where display is wanted.",
    materials: ["Wood veneer", "Soft-close hardware", "Internal lighting", "Leather pulls"],
    features: ["Made-to-measure wardrobe", "Open display shelving", "Internal organisers", "Matching side furniture"],
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
export const selectedProjects = featuredProjects.slice(0, 3);
export const featureStory = featuredProjects[3] || featuredProjects[0];
export const getProject = (slug) => projects.find((p) => p.slug === slug);
